### ISSUE TITLE
Buff problems

### ISSUE THREAD

**Issue by aureldussauge** [Nithanim/gw2api#2]
InfixUpgrade.Buff class does not contains any getters for skillId and description. Also, in the buff of this item https://api.guildwars2.com/v2/items/39276, the description contains some modifiers for attributes. I have to convert this string to a Map, and apply those modifiers on the attributes of the InfixUpgrade myself ?

**Comment by Nithanim** [comment]
I fixed the getters and setter.
The description is the same as the text that is displayed ingame and it makes it easy to display it on a item. I assume that you should not need to parse that but instead look it up by its skillId via /v2/skills. But since this endpoint is not active currently you have no other choice than parsing for now.
