### ISSUE TITLE
Trait facttypes not up to date

### ISSUE THREAD

**Issue by Carcharoth973** [Nithanim/gw2api#23]
Hey,
i am currently starting a projecet with your API.
When executing the following code, i get the Error:
Cannot invoke "me.nithanim.gw2api.v2.api.traits.FactType.getTypeClass()" because "type" is null.
`int[] temp = gwapi.specializations().getOverview();`
`specializations = gwapi.specializations().get(temp);`
`temp = gwapi.traits().getOverview();`
`traits = gwapi.traits().get(temp);`
The specializations work fine, but the traits not so much.
After digging a little into the problem, it seems like the first error occures in trait 257 [https://api.guildwars2.com/v2/traits/257](https://api.guildwars2.com/v2/traits/257). After checking the previous traits that loaded successfully, it seems, that the Facttype "StunBreak" is missing in your emnum and facttypes folder. 

Cheers

**Comment by Nithanim** [comment]
Thank you very much for reaching out! It is very possible that a lot of stuff is outdated or broken, since I have not updated it for a very long time. 

Sadly, I currently have multiple issues:
- JCenter: I released the library on JCenter but that has been shutdown (as in: read-only), so I cannot "just" release a new version. This will take me some time to sort that out.
- Building past Java 9 is not possible because of a dependency used.
- I also tried to modernize the core of the library (because there is a whole lot of crap in there) and ran into another issue in another dependency.

Would it be an issue for you if you clone this library locally, build it with `maven install` and use it with `<version>0.0.8-SNAPSHOT</version>` in the mean time?

Also: You must NOT request more than 200 ids in a single request. This is a limit of their API and results in an error message if you are slightly above and (somehow) HTTP 404 if too much over the limit. I added the `getAll()` methods because they work for this endpoint.

The stun break is not the only thiung that is broken. https://api.guildwars2.com/v2/traits/2123 "Life Force Cost" does not have a type which is also "new".

`gwapi.traits().getAll()` should now work for you on branch https://github.com/Nithanim/gw2api/tree/issue-23

I hope that helps you a little bit :)

**Comment by Nithanim** [comment]
Somehow it seems I got it working and version 0.0.8 is being published to maven central. This takes a bit of time. Pulling might work very soon but the index and [web interface](https://mvnrepository.com/artifact/me.nithanim.gw2api/gw2api?repo=central) take a long time. 

Please make sure to remove the `<repositories>` tag you added to your `pom.xml` (or gradle) because it is not needed anymore.

It would be great if you could report back if everything works for you now!

**Comment by Carcharoth973** [comment]
Hey, 
thanks for the quick responses!
So i just went into my project and since i am using gradle, i changed the implementation line to v0.0.8 and rebuild my application. (-> implementation 'me.nithanim.gw2api:gw2api:0.0.8')
Calling gw2api.traits().getAll(); works like a charm and gives me everything i could wish for :)
I also removed the JCenter repository form my build.gradle file.

Thanks alot!

**Comment by Nithanim** [comment]
Happy to help and glad it works for you now! If you have any more problems, don't hesitate to contact me again!
