### ISSUE TITLE
Duplicated class Transaction

### ISSUE THREAD

**Issue by aureldussauge** [Nithanim/gw2api#5]
The class Transaction exists in two location :
gw2api/src/main/java/me/nithanim/gw2api/v2/api/commerce/transactions/Transaction.java
gw2api/src/main/java/me/nithanim/gw2api/v2/api/commerce/exchange/Transaction.java

And why does the itemId field in Transaction is a long ?

**Comment by Nithanim** [comment]
You have a lot of good questions i really do not have any answers for. ;)
It is great that you are using this api and find all this little bugs. Please keep the reports coming!
I have to admit that I only built this api to be useful for others because I could not find a good one. I actually have never used it myself. So it is on you to make it better :)

**Comment by aureldussauge** [comment]
Great ! Could you update your library on jcenter please ?

**Comment by Nithanim** [comment]
Actually, I am currently working on it right now (fighting with maven...). I am tying to setup a snapshot repository so I don't have to increase the version number every time. And I want to make the deployment for me easier in general.

**Comment by Nithanim** [comment]
In theory we should now have 0.0.2 published. Since this is the first time I used the release plugin and published with it to bintray it/I might have messed up somewhere pretty badly. Could you please test if that worked?
PS: I don't really know what the release did to the git repository but I am running out of time today.

**Comment by aureldussauge** [comment]
I updated the dependency from 0.0.1 to 0.0.2 in my build.gradle file and it works. Thanks

**Comment by Nithanim** [comment]
Great that it worked! I will setup another repository for snapshots only in the future. In fact it is already there but I have to figure out how to deploy to there with the new deploy plugin in place. 
Further discussion about release and snapshots in #6
